modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = "https://github.com/AshIndigo/PrismaticEnchanter/issues"
license = "MIT"

[[mods]]
modId = "prismatic"
version = "${version}"
displayName = "Prismatic Enchanter"
authors = "Ash Indigo"
description = '''
TODO
'''
#logoFile = ""

[[dependencies.prismatic]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prismatic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prismatic]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"